const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='recoup-brand-review:v1';
const choices={'approved':'Keep','needs-changes':'Maybe','retired':'Pass'};
const groups=[['all','All assets'],['blog','Blog thumbnails'],['podcast','Podcast'],['logos','Logos & marks'],['backgrounds','Backgrounds'],['illustrations','Article illustrations'],['social','Social assets'],['picks','My picks']];
const library=location.pathname.endsWith('/experiments.html')?'experiments':'finals';
const libraryStage=library==='finals'?'final':'experiment';
let assets=[],reviews={},view='all',filter='all',query='',limit=24,active=null,toastTimer;
const knownStatuses=['proposed',...Object.keys(choices)];
function validated(data){if(!data||typeof data!=='object'||Array.isArray(data))throw Error('Invalid decisions');const next=Object.create(null);for(const [id,r] of Object.entries(data)){if(!r||!knownStatuses.includes(r.status)||typeof r.note!=='string'||r.note.length>2000)throw Error('Invalid entry');if(r.stage!==undefined&&!['final','experiment'].includes(r.stage))throw Error('Invalid page');next[id]={...(r.stage?{stage:r.stage}:{}),status:r.status,note:r.note,reviewer:typeof r.reviewer==='string'?r.reviewer.slice(0,80):'',date:typeof r.date==='string'?r.date:new Date().toISOString(),assetVersion:'1.0'};}return next;}
function status(id){return reviews[id]?.status||'proposed';}
function countReviewed(list){return list.filter(a=>choices[status(a.id)]).length;}
function stage(a){return reviews[a.id]?.stage||a.stage||'experiment';}
function inView(a,v=view){return stage(a)===libraryStage&&(v==='all'||v==='picks'&&['approved','needs-changes'].includes(status(a.id))||a.group===v);}
function stageButton(a){return `<button class="move-button" data-move="${esc(a.id)}">Move to ${stage(a)==='final'?'Experiments':'Finals'} ↗</button>`;}
function moveAsset(id){const a=assets.find(a=>a.id===id);if(!a)return;const next=stage(a)==='final'?'experiment':'final';reviews[id]={...reviews[id],status:status(id),note:reviews[id]?.note||'',stage:next,date:new Date().toISOString()};const persisted=save();renderGrid();if(active===id){$('#detail-stage').innerHTML=`<span class="stage-label">${next==='final'?'Final':'Experiment'}</span>${stageButton(a)}`;}notify(`Moved to ${next==='final'?'Finals':'Experiments'}${persisted?' · saved':' · session only'}`);}
function filtered(){return assets.filter(a=>inView(a)&&(filter==='all'||status(a.id)===(filter==='unreviewed'?'proposed':filter))&&`${a.title} ${a.code} ${a.collection}`.toLowerCase().includes(query));}
function notify(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(reviews));return true;}catch{$('#storage-note').textContent='Browser storage is unavailable. Your choices are kept for this session; export a backup before closing.';return false;}}
function choiceButtons(id){return `<div class="decisions" role="group" aria-label="Decision for ${esc(assets.find(a=>a.id===id)?.title)}">${Object.entries(choices).map(([s,label])=>`<button type="button" data-id="${esc(id)}" data-choice="${s}" aria-pressed="${status(id)===s}">${label}</button>`).join('')}</div>`;}
function renderNav(){ $('#categories').innerHTML=groups.filter(([id])=>library==='experiments'||id==='all'||id==='picks'||assets.some(a=>inView(a,id))).map(([id,label],i)=>`${i===7?'<div class="nav-break">':''}<button data-view="${id}" ${id===view?'aria-current="page"':''}>${label}<span>${assets.filter(a=>inView(a,id)).length}</span></button>${i===7?'</div>':''}`).join(''); }
function renderCounts(){const scope=assets.filter(a=>inView(a));$('#progress').innerHTML=`<strong>${scope.length}</strong>${library==='finals'?'final assets':'experiments'}`;for(const [page,key] of [['finals','final'],['experiments','experiment']]){$('#'+page+'-count').textContent=assets.filter(a=>stage(a)===key).length;}renderNav();}
function renderTabs(){$('#status-tabs').hidden=library==='finals';const opts=view==='picks'?[['all','All picks'],['approved','Keep'],['needs-changes','Maybe']]:[['all','All'],['unreviewed','Unreviewed'],...Object.entries(choices)];$('#status-tabs').innerHTML=opts.map(([id,label])=>`<button data-filter="${id}" aria-pressed="${id===filter}">${label}</button>`).join('');}
function card(a){const note=reviews[a.id]?.note;return `<article class="asset" data-card="${esc(a.id)}"><button class="preview ${a.dark?'dark':''}" data-open="${esc(a.id)}" aria-label="Preview ${esc(a.code)}: ${esc(a.title)}"><img loading="lazy" src="${esc(a.preview)}" alt="${esc(a.title)}">${a.video?'<span class="video-tag">▶ Motion</span>':''}</button><div class="asset-meta"><b>${esc(a.code)}</b><span>${esc(a.collection)}</span></div><h2>${esc(a.title)}</h2><div class="asset-footer">${library==='finals'?`<a class="download-primary" href="${esc(a.files[0]?.path||a.preview)}" download>Download ${esc(a.files[0]?.label||'asset')} ↓</a>`:choiceButtons(a.id)}<button class="note-button" data-open="${esc(a.id)}" data-note="true">${note?'Edit note':'Add note'} ↗</button></div><div class="asset-stage"><span class="stage-label">${stage(a)==='final'?'Final':'Experiment'}</span>${stageButton(a)}</div>${note?`<p class="note-excerpt">${esc(note)}</p>`:''}</article>`;}
function renderGrid(){const list=filtered();$('#grid').innerHTML=list.length?list.slice(0,limit).map(card).join(''):`<div class="empty"><h2>${view==='picks'?'Your shortlist starts here.':'No matching artwork.'}</h2><p>${view==='picks'?'Mark an asset Keep or Maybe to add it here.':'Try another category, search, or decision filter.'}</p><button data-reset>Clear filters</button></div>`;$('#result-count').textContent=`${Math.min(limit,list.length)} of ${list.length} assets${query?' matching your search':''}`;$('#more').hidden=limit>=list.length;$('#more').textContent=`Show ${Math.min(24,list.length-limit)} more`;renderCounts();}
function setView(v){if(!groups.some(g=>g[0]===v))v='all';view=v;filter='all';query='';limit=24;$('#search').value='';const label=groups.find(g=>g[0]===v)[1];$('#heading').textContent=v==='all'?(library==='finals'?'Finals.':'Experiments.'):(label+'.');$('#intro').textContent=library==='finals'?'Selected artwork and reusable templates. Download the version you need.':'Studies, alternatives, and ideas still in progress. Move an asset to Finals when you choose it.';$('#section-label').textContent=library.toUpperCase()+(v==='all'?'':' / '+label.toUpperCase());const u=new URL(location.href);u.pathname=u.pathname.replace(/[^/]*$/,library+'.html');u.searchParams.delete('view');if(v!=='all')u.searchParams.set('view',v);history.replaceState(null,'',u);renderTabs();renderGrid();}
function setChoice(id,s){if(!assets.some(a=>a.id===id)||!choices[s])return;reviews[id]={...reviews[id],status:status(id)===s?'proposed':s,note:reviews[id]?.note||'',reviewer:reviews[id]?.reviewer||'',date:new Date().toISOString(),assetVersion:'1.0'};const persisted=save();renderGrid();if(active===id)$('#detail-choices').innerHTML=choiceButtons(id);notify(`${choices[status(id)]||'Decision cleared'}${persisted?' · saved':' · session only'}`);}
function openAsset(id,noteFocus=false){const a=assets.find(x=>x.id===id);if(!a)return;active=id;$('#detail-body').innerHTML=`<div class="detail-layout"><div class="detail-art ${a.dark?'dark':''}">${a.video?`<video controls playsinline preload="metadata" src="${esc(a.video)}" poster="${esc(a.preview)}"></video>`:`<img src="${esc(a.preview)}" alt="${esc(a.title)}">`}</div><div class="detail-info"><p class="eyebrow">${esc(a.code)} / ${esc(a.collection)}</p><h2 id="detail-title">${esc(a.title)}</h2><div id="detail-stage" class="asset-stage"><span class="stage-label">${stage(a)==='final'?'Final':'Experiment'}</span>${stageButton(a)}</div><div id="detail-choices">${choiceButtons(id)}</div><label for="note">What works? What should change?</label><textarea id="note" maxlength="2000" placeholder="Keep the colors, change the type…">${esc(reviews[id]?.note||'')}</textarea><button id="save-note" class="primary">Save note</button><p class="note-help" id="note-state">Notes stay with this asset.</p><div class="downloads">${a.files.map(f=>`<a href="${esc(f.path)}" download>${esc(f.label)} ↓</a>`).join('')}</div>${a.tool?`<a class="tool-link" href="${esc(a.tool)}">Open editor / source ↗</a>`:''}</div></div>`;$('#detail').showModal();if(noteFocus)$('#note').focus();$('#note').addEventListener('input',()=>{$('#note-state').textContent='Unsaved note';});}
function saveNote(){if(!active)return;reviews[active]={...reviews[active],status:status(active),note:$('#note').value.trim(),reviewer:reviews[active]?.reviewer||'',date:new Date().toISOString(),assetVersion:'1.0'};const persisted=save();$('#note-state').textContent=persisted?'Note saved in this browser.':'Note kept for this session. Export a backup.';renderGrid();}
function closeDetail(){if(active&&$('#note')?.value.trim()!==(reviews[active]?.note||''))saveNote();$('#detail video')?.pause();$('#detail').close();active=null;}
function summaryText(){const lines=['Recoup Brand Studio — review','', 'FINALS',...assets.filter(a=>stage(a)==='final').map(a=>`${a.code} — ${a.title} [${a.id}]`),'', 'PAGE MOVES',...assets.filter(a=>reviews[a.id]?.stage).map(a=>`${a.code} — ${a.title}: ${stage(a)==='final'?'Finals':'Experiments'}`),''];for(const s of Object.keys(choices)){const selected=assets.filter(a=>status(a.id)===s);if(!selected.length)continue;lines.push(choices[s].toUpperCase());for(const a of selected){lines.push(`${a.code} — ${a.title} [${a.id}]`);if(reviews[a.id]?.note)lines.push(`  Note: ${reviews[a.id].note}`);lines.push(`  Asset: ${a.preview}`);}lines.push('');}const notes=assets.filter(a=>status(a.id)==='proposed'&&reviews[a.id]?.note);if(notes.length){lines.push('NOTES / NO DECISION');for(const a of notes)lines.push(`${a.code} — ${a.title}: ${reviews[a.id].note}`);}if(lines.length===2)lines.push('No decisions yet.');return lines.join('\n');}
function showSummary(){$('#summary-text').value=summaryText();$('#summary').showModal();}
function download(data,type,name){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);}
async function start(){const res=await fetch('review-board-assets.json');if(!res.ok)throw Error('The artwork index could not load.');assets=await res.json();const featured=['linkedin-art-blue-sweep','blue-sweep-podcast-title','blue-sweep-podcast-white-logo'];assets.sort((a,b)=>(featured.includes(a.id)?featured.indexOf(a.id):featured.length)-(featured.includes(b.id)?featured.indexOf(b.id):featured.length));try{reviews=validated(JSON.parse(localStorage.getItem(KEY)||'{}'));}catch{reviews={};$('#storage-note').textContent='Existing browser decisions could not be read. Export this session before leaving; the earlier studio is still available.';}
 document.title='Recoup Brand Studio — '+(library==='finals'?'Finals':'Experiments');
 document.body.dataset.library=library;
 document.querySelector(`[data-page="${library}"]`).setAttribute('aria-current','page');
 $('#page-context').textContent='YOUR BRAND / '+library.toUpperCase();
 $('#review-hint').hidden=library==='finals';
 $('#library-note').innerHTML=library==='finals'?'<strong>Your selected direction.</strong><span>Blue sweep banners, podcast templates, and the core identity. Earlier versions live in <a href="experiments.html">Experiments ↗</a>.</span>':'<strong>Room to explore.</strong><span>Keep / Maybe / Pass builds your shortlist. <b>Move to Finals</b> makes an asset part of your final library.</span>';
 document.querySelectorAll('[data-library]').forEach(el=>el.hidden=el.dataset.library!==library);
 setView(new URL(location.href).searchParams.get('view')||'all');
 $('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){setView(b.dataset.view);window.scrollTo({top:0});}});
 $('#status-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;limit=24;renderTabs();renderGrid();}});
 $('#search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();limit=24;renderGrid();});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(b)setChoice(b.dataset.id,b.dataset.choice);const o=e.target.closest('[data-open]');if(o)openAsset(o.dataset.open,Boolean(o.dataset.note));if(e.target.closest('[data-reset]'))setView('all');const m=e.target.closest('[data-move]');if(m)moveAsset(m.dataset.move);if(e.target.id==='save-note')saveNote();});
 $('#more').addEventListener('click',()=>{limit+=24;renderGrid();});$('#close').addEventListener('click',closeDetail);$('#detail').addEventListener('cancel',e=>{e.preventDefault();closeDetail();});$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=$('#detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDetail();}});
 $('#copy-picks').addEventListener('click',showSummary);$('#summary-close').addEventListener('click',()=>$('#summary').close());$('#copy-summary').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#summary-text').value);notify('Copied. Paste the summary into our conversation.');}catch{$('#summary-text').focus();$('#summary-text').select();notify('Select and copy the highlighted summary.');}});
 $('#export-json').addEventListener('click',()=>download(JSON.stringify({schema:'recoup-brand-review-v1',exportedAt:new Date().toISOString(),reviews},null,2),'application/json','recoup-brand-decisions.json'));
 $('#export-text').addEventListener('click',()=>download(summaryText(),'text/plain','recoup-brand-picks.txt'));
 $('#import').addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('File too large');const data=JSON.parse(await f.text());if(data.schema!=='recoup-brand-review-v1')throw Error('Wrong format');const incoming=validated(data.reviews);for(const [id,r] of Object.entries(incoming))reviews[id]={...reviews[id],...r};const persisted=save();renderGrid();notify(persisted?'Decisions imported and saved.':'Imported for this session; export a backup.');}catch{notify('Choose a valid Recoup decisions JSON export under 1 MB.');}finally{e.target.value='';}});
 window.addEventListener('storage',e=>{if(e.key===KEY){try{reviews=validated(JSON.parse(e.newValue||'{}'));renderGrid();if(active)$('#detail-choices').innerHTML=choiceButtons(active);}catch{notify('Could not read updated decisions from another tab.');}}});
}
start().catch(e=>{$('#grid').innerHTML=`<div class="empty"><h2>Could not load the review board.</h2><p>${esc(e.message)}</p><a href="explore.html">Open the earlier studio</a></div>`;});
