import type { Metadata } from "next";
import { buildPageMetadata } from "@/lib/seo";
import { siteConfig } from "@/lib/config";

export const metadata: Metadata = buildPageMetadata({
  title: "Terms of Service | Recoupable",
  description: "Terms and conditions for using Recoupable services.",
  path: "/terms",
});

/**
 * Terms of service page — required for legal compliance.
 */
export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-4xl font-bold tracking-tight mb-8">
        Terms of Service
      </h1>
      <div className="prose prose-lg max-w-none text-[var(--foreground)]">
        <p className="text-[var(--muted-foreground)]">
          Last updated: March 16, 2026
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using recoupable.com and related services
          (&ldquo;Services&rdquo;), you agree to be bound by these Terms of
          Service. If you do not agree, do not use the Services.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          Recoupable provides AI-powered music marketing tools and services,
          including content creation, audience analysis, and social media
          management. Services are provided &ldquo;as is&rdquo; and may change
          over time.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          Some features require an account at{" "}
          <a href={siteConfig.appUrl}>{siteConfig.appUrl}</a>. You are
          responsible for maintaining the security of your account and all
          activity under it.
        </p>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Services for any unlawful purpose</li>
          <li>
            Attempt to gain unauthorized access to any part of the Services
          </li>
          <li>Interfere with or disrupt the Services</li>
          <li>
            Use the Services to generate content that infringes on third-party
            rights
          </li>
        </ul>

        <h2>5. Intellectual Property</h2>
        <p>
          Content generated by the AI tools is provided for your use. You retain
          rights to content you create using the Services. Recoupable retains
          rights to the platform, software, and brand assets.
        </p>

        <h2>6. Newsletter & Communications</h2>
        <p>
          By subscribing to our newsletter, you consent to receiving periodic
          emails from Recoupable. You can unsubscribe at any time via the link in
          each email.
        </p>

        <h2>7. Limitation of Liability</h2>
        <p>
          Recoupable is provided &ldquo;as is&rdquo; without warranties of any
          kind. We are not liable for any indirect, incidental, or consequential
          damages arising from your use of the Services.
        </p>

        <h2>8. Changes to Terms</h2>
        <p>
          We may update these terms from time to time. Continued use of the
          Services after changes constitutes acceptance of the new terms.
        </p>

        <h2>9. Contact</h2>
        <p>
          Questions about these terms? Email us at{" "}
          <a href={`mailto:${siteConfig.supportEmail}`}>
            {siteConfig.supportEmail}
          </a>
          .
        </p>
      </div>
    </div>
  );
}
