import { withPageMetadata } from "@/lib/seo";
import type { Metadata } from "next";
import Link from "next/link";
import { SkyArrow } from "@/components/sky/arrow";
import { MarketingPage, PageHero, PageSection, PageButton, PageCTA } from "@/components/marketing-migration/ui";

export const metadata: Metadata = withPageMetadata({ title:"AI for music funds, catalog owners, labels & artists", description:"Explore how Recoup helps music funds, rightsholders, labels, distributors, and artists with AI strategy, custom systems, and music operations.", alternates:{canonical:"/solutions"} });
const segments = [
 {id:"catalog-owners",label:"MUSIC FUNDS & CATALOG OWNERS",title:"Put your catalog’s information to work.",description:"Connect the documents, numbers, and decisions behind your catalog. Start with the job your team needs to improve.",href:"/acquisitions",cta:"Explore acquisition review",items:[{title:"Acquisition preparation",body:"Organize deal documents, identify missing information, and prepare questions with the sources behind them."},{title:"Royalty reporting",body:"Match statements and receipts, prepare reports, and keep unresolved entries visible for review."},{title:"Catalog search",body:"Use your metadata and a creative brief to find relevant tracks in your permissioned catalog."},{title:"Management briefs",body:"Bring recurring updates and research into a briefing your team can check and use."}]},
 {id:"labels",label:"LABELS & RIGHTSHOLDERS",title:"More attention for every release.",description:"Build repeatable methods for research, creative work, reporting, and release planning across your roster.",href:"/platform",cta:"Explore the platform",items:[{title:"Artist research",body:"Bring artist, audience, and social context together for a useful research brief."},{title:"Creative preparation",body:"Develop campaign concepts, content briefs, and drafts with your artist’s voice in context."},{title:"Recurring reporting",body:"Set up reports that surface what changed and what deserves attention."},{title:"Release planning",body:"Turn the release brief into a sequence of work your team can review and coordinate."}]},
 {id:"distributors",label:"DISTRIBUTORS",title:"Make your services easier to repeat.",description:"Connect roster information and the services you provide, with workflows that fit your artists and internal team.",href:"/build",cta:"Explore custom builds",items:[{title:"Roster onboarding",body:"Organize artist profiles and source information into a consistent working context."},{title:"Cross-roster reporting",body:"Bring updates across artists into a view that helps your team prioritize."},{title:"Embedded experiences",body:"Build music tools and agent interactions into your own product through the API."},{title:"Artist services",body:"Develop research and content workflows your team can deliver consistently."}]},
 {id:"artists",label:"ARTISTS & MANAGERS",title:"Keep the music moving.",description:"Use the Recoup platform and Skills for research, content ideas, release plans, and the recurring work around your music.",href:"/pricing",cta:"Explore the platform plan",items:[{title:"Artist context",body:"Give your agent the information it needs about the artist, the music, and the audience."},{title:"Campaign development",body:"Prepare content ideas and a release plan, then refine them in your own voice."},{title:"Audience research",body:"Explore artist and social information to inform where you spend your attention."},{title:"Scheduled tasks",body:"Run recurring reports and research on a cadence that fits your plan."}]},
];
export default function SolutionsPage(){return <MarketingPage><PageHero eyebrow="SOLUTIONS" title={<>Built for the business<br /><span>around the music.</span></>} description="From catalog acquisitions to the next release, Recoup connects AI to the work your company actually does."><PageButton href="/contact">Talk about your team</PageButton></PageHero><nav className="mm-pill-nav" aria-label="Explore solutions">{segments.map(item=><a href={`#${item.id}`} key={item.id}>{item.id==="catalog-owners"?"Funds & catalog owners":item.id==="labels"?"Labels":item.id==="artists"?"Artists & managers":"Distributors"}</a>)}</nav><PageSection>{segments.map(segment=><section className="mm-solution" id={segment.id} key={segment.id}><div><p className="sp-kicker">{segment.label}</p><h2>{segment.title}</h2><p>{segment.description}</p><Link href={segment.href} className="sp-text-link">{segment.cta}<SkyArrow /></Link></div><div className="mm-solution-items">{segment.items.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>)}</PageSection><PageCTA title="Your workflow might be the next one." description="Tell us where your team gets stuck. We’ll talk through what a useful first build could look like." /></MarketingPage>;}
